length=float(input("enter the length of a cubiod"))
width=float(input("enter the width a cuboid"))
height=float(input("enter the height of a cuboid"))
print("surface area of cubiod")
print(the volumn of cubiod')
print("the surface area')
